[package]
name = "signature-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { package = "const-hex", version = "1.6", features = ["hex"] }
ring = "0.17.8"
anyhow = "1.0.86"
